# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('city_text', models.CharField(max_length=200)),
                ('state_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantManager'),
        ),
    ]
